language: go
go:
  - 1.3

before_script:
  - export QINIU_ACCESS_KEY="QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm"
  - export QINIU_SECRET_KEY="Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz"
  - export QINIU_TEST_BUCKET="gosdk"
  - export QINIU_TEST_DOMAIN="gosdk.qiniudn.com"

script:
  - GOPATH=`pwd`/../checkstyle && cd .. && mkdir -p checkstyle; cd checkstyle && go get github.com/qiniu/checkstyle/gocheckstyle"
  - ../checkstyle/bin/gocheckstyle -config=.go_style .
